image = "ghcr.io/queil/image:dotnet-7"
shell = "bash"
caches = [
  "~/.nuget"
]

[sidecars.nats]
image = "docker.io/nats:2"
command = ["--js"]
mounts = ["/tmp/nats/jetstream"]

[sidecars.probe]
image = "ghcr.io/queil/probe:latest"

[sidecars.probe.env]
NATS_URL = "nats:4222"
