name: Release

on:
  push:
    tags: '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create GitHub release
      uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0 # v2.0.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ env.RELEASE_TAG }}
        tag_name: ${{ env.RELEASE_TAG }}
        draft: ${{ env.DRAFT_RELEASE }}
        prerelease: ${{ env.PRE_RELEASE }}
        body: "Initial release"

  build-release:
    name: Build Release
    needs: create-release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_target: x86_64-unknown-linux-gnu
          - os: macos-latest
            build_target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: rustc add target
        if: matrix.os == 'macos-latest'
        run: rustup target add aarch64-apple-darwin

      - name: build
        run: |
          cargo build --release --verbose --target ${{ matrix.build_target }}
          mv target/${{ matrix.build_target }}/release/rooz target/${{ matrix.build_target }}/release/rooz-${{ matrix.build_target }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: target/${{ matrix.build_target }}/release/rooz-${{ matrix.build_target }}
