name: Release

on:
  push:
    tags: '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - name: Create GitHub release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ env.RELEASE_TAG }}
        tag_name: ${{ env.RELEASE_TAG }}
        draft: ${{ env.DRAFT_RELEASE }}
        prerelease: ${{ env.PRE_RELEASE }}
        body: "Initial release"
        files: |
          target/release/rooz
         
